### ISSUE TITLE
v12 roadmap

### ISSUE THREAD

**Issue by atreyasha** [archlinux-downgrade/downgrade#186]
This is a summary of planned developments leading up to `v12.0.0`.

## Major features

Split `downgrade` into independent/modular scripts (eg. `downgrade-search`, `downgrade-select` and `downgrade-install`; see #181) and thereby address these issues:

- [ ] Make `fzf` (and other TUIs) optional dependencies (with default package selection) and integrate into `PKGBUILD`
- #180
- [ ] Migrate to `getopts` to handle CLI arguments in lower-level scripts
- #182
- [ ] Use `pacman-conf` everywhere for `pacman.conf` parsing
- #171
- [ ] Reintroduce `--arch` CLI option and possibly `arch` column in selection
- #185
- #176
- [x] Develop a prototype version of `pacignore` and integrate it into `downgrade`
- #158

## Bugfixes

- [x] Use first architecture from `pacman-conf Architecture`
- #185
- [x] Add additional check for header in case `IgnorePkg` string is missing in `pacman.conf`
- #183
- [x] Catch `sed` error messages on invalid input
- #184

## Miscellaneous

- [x] Contact `pacman-dev` and/or `pacman-contrib` mailing lists to ask regarding additional `pacignore` script
- #183 
- #158
- Email sent to `pacman-contrib` mailing list, pending discussion
- Implementing `pacignore` as part of `pacman-contrib` does not seem practical based on the response we received, so it makes more sense for us to implement it ourselves first and then contact the mailing list again regarding possible integration
- [x] Update URL for `downgrade` in `PKGBUILD` to `github.com/archlinux-downgrade/downgrade`

Feel free to add or edit these points. Thanks :)

**Comment by pbrisbin** [comment]
Added a `v12` Milestone and tagged the still-open Issues listed here. Going to close this now and track it that way.
